import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts src/types`.

export enum OrderItemLeatherType {
    PVC = "PVC",
    HALF_LEATHER = "HalfLeather",
    FULL_LEATHER = "FullLeather"
}

export enum OrderItemSeatReplacementScope {
    WHOLE = "Whole",
    PARTIAL = "Partial"
}

export type ProductType = Models.Row & {
    name: string;
    isSystem: boolean;
}

export type Client = Models.Row & {
    name: string;
}

export type CarModel = Models.Row & {
    name: string;
    carBrand: CarBrand;
}

export type CarBrand = Models.Row & {
    name: string;
    carModels: CarModel[];
}

export type PoNumberSequence = Models.Row & {
    nextValue: number;
}

export type InvoiceNumberSequence = Models.Row & {
    nextValue: number;
    entity: string;
}

export type OrderItem = Models.Row & {
    productType: string;
    leatherType: OrderItemLeatherType | null;
    seatReplacementScope: OrderItemSeatReplacementScope | null;
    partialSetDetails: string | null;
    color: string | null;
    thread: string | null;
    doorPanelDetails: string | null;
    designDetails: string | null;
    details: string | null;
    unitPriceExclTax: number;
    isBtProduction: boolean;
    btProductionScope: string | null;
    isSgProduction: boolean;
    sgProductionScope: string | null;
    isSgReadyStock: boolean;
    sgReadyStockScope: string | null;
    replaceStock: boolean;
    order: Order;
}

export type Order = Models.Row & {
    orderDate: string;
    invoiceNumber: string;
    poNumber: string;
    client: string;
    salesperson: string | null;
    clientDetails: string | null;
    carBrand: string;
    carModel: string;
    carPlate: string;
    billingComments: string | null;
    handoverDate: string | null;
    taxRate: number;
    subtotalExclTax: number;
    totalTax: number;
    totalInclTax: number;
    orderItems: OrderItem[];
}
