import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts src/types`.

export type ProductTypes = Models.Row & {
    name: string;
    isSystem: boolean;
}

export type Clients = Models.Row & {
    name: string;
}
