import type { Models } from "appwrite";

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts packages/shared-types/src/appwrite`.

export enum OrderItemLeatherType {
  PVC = "PVC",
  HALF_LEATHER = "HalfLeather",
  FULL_LEATHER = "FullLeather",
}

export enum OrderItemSeatReplacementScope {
  WHOLE = "Whole",
  PARTIAL = "Partial",
}

export enum InvoiceStatus {
  OPEN = "Open",
  PAID = "Paid",
  CANCELLED = "Cancelled",
}

export enum InvoiceEntity {
  FIVE_STAR_AUTO_LEATHER = "FiveStarAutoLeather",
  LEATHER_AND_STITCH = "LeatherAndStitich",
}

export type ProductType = Models.Row & {
  name: string;
  isSystem: boolean;
};

export type Client = Models.Row & {
  name: string;
};

export type CarBrand = Models.Row & {
  name: string;
};

export type OrderItem = Models.Row & {
  productType: string;
  leatherType: OrderItemLeatherType | null;
  seatReplacementScope: OrderItemSeatReplacementScope | null;
  partialSetDetails: string | null;
  color: string | null;
  thread: string | null;
  doorPanelDetails: string | null;
  designDetails: string | null;
  details: string | null;
  isBtProduction: boolean;
  btProductionScope: string | null;
  isSgProduction: boolean;
  sgProductionScope: string | null;
  isSgReadyStock: boolean;
  sgReadyStockScope: string | null;
  replaceStock: boolean;
  order: Order;
};

export type Order = Models.Row & {
  orderDate: string;
  poNumber: string;
  client: string;
  clientDetails: string | null;
  carBrand: string;
  carModel: string;
  carPlate: string;
  handoverDate: string | null;
  orderItems: OrderItem[];
  completedDate: string | null;
  remarks: string | null;
  invoices: Invoice[];
  batamProductionStatus: string | null;
  sgProductionStatus: string | null;
  installationStatus: string;
};

export type InvoiceItem = Models.Row & {
  title: string;
  description: string | null;
  unitPriceExclTax: number;
  invoice: Invoice;
};

export type Invoice = Models.Row & {
  invoiceEntity: InvoiceEntity;
  invoiceNumber: string;
  taxRate: number;
  subtotalExclTax: number;
  totalTax: number;
  totalInclTax: number;
  billingComments: string | null;
  openDate: string;
  cancelledDate: string | null;
  paidDate: string | null;
  status: InvoiceStatus;
  client: string;
  clientDetails: string | null;
  carBrand: string;
  carModel: string;
  carPlate: string;
  invoiceItems: InvoiceItem[];
  order: Order;
};

export type NextNumberSequence = Models.Row & {
  nextValue: number;
  key: string;
};
